name: heph-sparse-set
version: 0.1.0.0
github: "jtnuttall/heph"
license: BSD-3-Clause
author: "Jeremy Nuttall"
maintainer: "jeremy@jeremy-nuttall.com"
copyright: "2025 Jeremy Nuttall"

extra-doc-files:
  - README.md
  - LICENSE
  - CHANGELOG.md

synopsis: Really fast mutable sparse sets
category: Data Structures
tested-with: GHC == 9.8.4 || == 9.6.5 || == 8.10.7

build-type: Simple

default-extensions:
  # Minimal set from GHC2021 to support GHC <9.2
  - BangPatterns
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - FlexibleContexts
  - ImportQualifiedPost
  - NumericUnderscores
  - RankNTypes
  - StandaloneDeriving
  - TupleSections
  - TypeApplications

  # Other modern extensions
  - BlockArguments
  - DerivingStrategies
  - LambdaCase
  - RecordWildCards

description: Please see the README on GitHub at <https://github.com/jtnuttall/heph/tree/main/heph-sparse-set#readme>
homepage: https://github.com/jtnuttall/heph/tree/main/heph-sparse-set#readme

dependencies:
  - base >= 4.7 && < 5
  - deepseq >= 1.4 && < 1.6
  - primitive >= 0.7 && < 0.10
  - vector >= 0.12.3.0 && < 0.14

ghc-options:
  - -Wall
  - -Wcompat

library:
  source-dirs: src
  ghc-options:
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints

tests:
  heph-sparse-set-test:
    main: Driver.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - heph-sparse-set
      - containers >= 0.6.2 && < 0.8
      - hedgehog >= 1.0.4 && < 1.6
      - nothunks >= 0.1.3.0 && < 0.4
      - tasty >= 1.4.1 && < 1.6
      - tasty-discover >= 4.2.1 && < 6
      - tasty-hedgehog >= 1.1 && < 1.5
      - tasty-hunit >= 0.10 && < 0.11
    build-tools:
      - tasty-discover

benchmarks:
  heph-sparse-set-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
    dependencies:
      - heph-sparse-set
      - containers
      - deepseq
      - mtl >= 1.2 && < 2.4
      - random >= 0.3.3 && < 1.3
      - criterion >= 1.5.9 && < 1.7
