name: heph-aligned-storable
version: 0.1.0.0
github: "jtnuttall/heph"
license: BSD-3-Clause
author: "Jeremy Nuttall"
maintainer: "jeremy@jeremy-nuttall.com"
copyright: "2025 Jeremy Nuttall"
tested-with: GHC == 9.8.4 || == 9.6.5 || == 8.10.7 || == 8.10.4

extra-doc-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
synopsis: Generically derive Storable instances suitable for CPU-GPU transfer
category: Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at
  <https://github.com/jtnuttall/heph/tree/main/heph-aligned-storable#readme>
homepage: https://github.com/jtnuttall/heph/tree/main/heph-aligned-storable#readme

dependencies:
  - base >= 4.7 && < 5
  - half >= 0.3 && < 0.5
  - hashable >= 1.3 && < 1.6
  - linear >= 1.20 && < 1.24
  - unliftio >= 0.2 && < 0.3
  - vector >= 0.12.3.0 && < 0.14
  - vector-sized >= 1.4 && < 1.7
  - template-haskell >= 2.14 && < 2.24
  - th-abstraction >= 0.4 && < 0.8

ghc-options:
  - -Wall
  - -Wcompat

library:
  source-dirs: src
  ghc-options:
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints

tests:
  heph-aligned-storable-test:
    main: Driver.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - heph-aligned-storable
      - bytestring >= 0.10 && < 0.13
      - hedgehog >= 1.0.4 && < 1.6
      - lifted-base >= 0.2 && < 0.3
      - monad-control >= 1.0 && < 1.1
      - tasty >= 1.4.1 && < 1.6
      - tasty-discover >= 4.2.1 && < 6
      - tasty-hedgehog >= 1.1 && < 1.5
      - tasty-hunit >= 0.10 && < 0.11
      - tasty-inspection-testing >= 0.1 && < 0.3
