name: Haskell CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resolver: ["lts-23.24", "lts-22.20", "lts-18.28", "lts-18.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          resolver: ${{ matrix.resolver }}
          stack-version: 'latest'
          cache-key: ${{ runner.os }}-haskell-stack-${{ hashFiles('stack.yaml') }}-${{ matrix.resolver }}

      - name: Cache Stack work directory
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ matrix.resolver }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ matrix.resolver }}-

      - name: Install dependencies (and heph-sparse-set)
        run: stack build --test --bench --only-dependencies

      - name: Build and run tests
        run: stack test --no-build

      - name: Install fourmolu (for formatting check)
        run: |
          stack install fourmolu
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check formatting with fourmolu
        run: fourmolu --check heph-sparse-set/src heph-sparse-set/test heph-sparse-set/bench
