name: Haskell CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - resolver: "lts-23.24"
            ghc_display: "9.8.4"
          - resolver: "lts-22.20"
            ghc_display: "9.6.5"
          - resolver: "lts-18.28"
            ghc_display: "8.10.7"

    name: ${{ matrix.ghc_display }} (${{ matrix.resolver }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          resolver: ${{ matrix.resolver }}
          stack-version: 'latest'

      - name: Cache Stack work directory
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ matrix.resolver }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ matrix.resolver }}-

      - name: Install dependencies (and heph-sparse-set)
        run: stack build --test --bench --only-dependencies

      - name: Build and run tests
        run: stack test --no-build

      - name: Install fourmolu
        run: |
          stack install fourmolu
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check formatting with fourmolu
        run: fourmolu --check heph-sparse-set/src heph-sparse-set/test heph-sparse-set/bench
